#!/bin/bash

# ../params_decided.params_frequency.txt was generated by running
#   hybsel-design-runs/scripts/count_params_frequency.sh
# on ../params_decided.txt
Rscript ../../../../../scripts/plot_bubble_chart_of_probe_parameters.R ../params_decided.params_frequency.txt params_decided.params_frequency.pdf -1,0,1,2,3,4,5,6 -10,0,10,20,30,40,50,60
